---
- name: Install libaio1
  apt:
     name: "{{ item }}"
     state: present
  loop:
  - libaio1
  - libtinfo5
  register: result
  until: result is not failed
  retries: 5
  delay: 5
- name: Create mysql group 
  group:
     name: mysql
     state: present
- name: Create mysql user
  user:
     name: mysql
     group: mysql
     shell: /bin/false
     state: present
- name: Create download directory
  file:
     path: "{{ download_dir }}"
     state: directory
     mode: "0755"
- name: Check if package have been downloaded
  stat:
     path: "{{ download_dir }}/{{ ndb_package }}"
  register: f
- name: Download NDB into download_dir
  get_url:
     url: "{{ ndb_tar_gz }}"
     dest: "{{ download_dir }}/{{ ndb_package }}"
  when: not f.stat.exists
- name: Unpack the NDB in download_dir
  unarchive:
     src: "{{ download_dir }}/{{ ndb_package }}"
     dest: "{{ download_dir }}"
     remote_src: yes
     owner: root
     group: mysql
- name: Link unpacked directory to /usr/local/mysql
  file:
     src: "{{ download_dir }}/{{ ndb_dir }}"
     dest: "/usr/local/mysql"
     state: link

- name: Generate /etc/my.cnf configuration file for all the nodes
  vars:
     sql_node: "{{ hostvars['node-0'].ansible_host }}"
  template:
     src: "./files/my.cnf.j2"
     dest: "/etc/my.cnf"
