---
- name: Install libaio1
  apt:
     name: libaio1
     state: present
  loop:
  - libaio1
  - libtinfo5
- name: Create mysql group 
  group:
     name: mysql
     state: present
- name: Create mysql user
  user:
     name: mysql
     group: mysql
     shell: /bin/false
     state: present
- name: Create download directory
  file:
     path: "{{ download_dir }}"
     state: directory
     mode: "0755"
- name: Check if package have been packed
  stat:
     path: "{{ download_dir }}/{{ ndb_dir }}"
  register: f
- name: Unpack the NDB in download_dir
  unarchive:
     src: "{{ ndb_tar_gz }}"
     dest: "{{ download_dir }}"
     remote_src: yes
  when: not f.stat.exists
- name: Link unpacked directory to /usr/local/mysql
  file:
     src: "{{ download_dir }}/{{ ndb_dir }}"
     dest: "/usr/local/mysql"
     state: link

