---
# tasks file for replica
- name: Copy data node daemons to /usr/local/bin
  file:
     src: "{{ download_dir }}/{{ ndb_dir }}/bin/{{ item }}"
     dest: "/usr/local/bin/{{ item }}"
     state: link
  loop:
  - ndbd
  - ndbmtd
