---
# tasks file for replica
- name: Copy data node daemons to /usr/local/bin
  file:
     src: "{{ download_dir }}/{{ ndb_dir }}/bin/{{ item }}"
     dest: "/usr/local/bin/{{ item }}"
     state: link
  loop:
  - ndbd
  - ndbmtd

- name: Generate /etc/my.cnf configuration file
  vars:
     sql_node: "{{ hostvars['node-0'].ansible_host }}"
  template:
     src: "./files/my.cnf.j2"
     dest: "/etc/my.cnf"

- name: Copy ndbd service file to /lib/systemd/system
  src: "./files/ndbd.service"
  dest: "/lib/systemd/system/ndbd.service"

- name: Start data node service
  systemd:
     daemon_reload: yes
     name: ndbd
     state: restarted
